[package]
name = "tantalum_unit"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2.6.0"
num = "0.4.3"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false